app:
  name: go-web
  mode: debug
  author: 靓仔
  email: nieqiurong@163.com
  qq: 996102919
server:
  port: 8080
datasource:
  username: root
  password: 123456
  dbName: test
  host: 127.0.0.1
  port: 3306
  maxIdle: 5
  maxOpen: 20
  maxLifetime: 5m
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
jwt:
  key: m28stme12h3s19ia
  time: 1h
